### ISSUE TITLE
Error if only one Private Data

### ISSUE THREAD

**Issue by fclausset** [lolautruche/LolautruchePaylineBundle#1]
If only one Private Data is added to a WebTransaction as in the exemple.
`->addPrivateData('someInternalVariable', '123xyz456')`

We get an error in Payline/PaylineResult.php at line 67 since $this->resultHash['privateDataList']['privateData'] is not an array of privateData but the private data Itself. 

It works if we add two or more private Data to the WebTransaction

**Comment by lolautruche** [comment]
Thanks for the report @fclausset

**Comment by lolautruche** [comment]
@fclausset Could you please post the exact error message with the stack trace?

Thanks

**Comment by lolautruche** [comment]
OK I managed to reproduce it:

```
Illegal string offset 'key'
 /Users/lolautruche/workspace/symfony/payline-bundle/Payline/PaylineResult.php:67
```

I updated #2 accordingly, and updated the test.

**Comment by lolautruche** [comment]
Tagged `v1.0.1`
