### ISSUE TITLE
Symfony 3.0.3 lock

### ISSUE THREAD

**Issue by sohelzerdoumi** [lolautruche/LolautruchePaylineBundle#14]
Hi,
i can't use your bundle with a higher version of symfony (3.0.9)
can you be more permissive with requirements?

"symfony/symfony": "^2.7.10|>=3.0.3"
thx

-----
$ composer update
  Problem 1
    - Conclusion: remove symfony/symfony v3.0.9

**Comment by sohelzerdoumi** [comment]
I updated to symfony 3.4 and it work...

**Comment by lolautruche** [comment]
Hi @sohelzerdoumi . Glad to see that you finally nailed it. What was the issue ? Because the dependency to `symfony/symfony` is already very permissive.

**Comment by sohelzerdoumi** [comment]
This issue occured because of another package "doctrine/doctrine-fixtures-bundle"

>   Problem 1
    - Conclusion: don't install symfony/symfony v3.0.9
    - Conclusion: don't install symfony/symfony v3.0.8
    - Conclusion: don't install symfony/symfony v3.0.7
    - Conclusion: don't install symfony/symfony v3.0.6
    - Conclusion: don't install symfony/symfony v3.0.5
    - Installation request for doctrine/doctrine-fixtures-bundle 2.2.*@dev -> satisfiable by doctrine/doctrine-fixtures-bundle[v2.2.0, v2.2.1, 2.2.x-dev].
    - Conclusion: don't install symfony/symfony v3.0.4
    - lolautruche/payline-bundle v1.1.2 requires symfony/symfony ^2.7.10|^3.0.3 -> satisfiable by symfony/symfony[v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9].
    - lolautruche/payline-bundle v1.0.0 requires symfony/symfony ^2.7.10|^3.0.3 -> satisfiable by symfony/symfony[v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9].
    - lolautruche/payline-bundle v1.0.1 requires symfony/symfony ^2.7.10|^3.0.3 -> satisfiable by symfony/symfony[v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9].
    - lolautruche/payline-bundle v1.0.2 requires symfony/symfony ^2.7.10|^3.0.3 -> satisfiable by symfony/symfony[v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9].
    - lolautruche/payline-bundle v1.1.0 requires symfony/symfony ^2.7.10|^3.0.3 -> satisfiable by symfony/symfony[v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9].
    - lolautruche/payline-bundle v1.1.1 requires symfony/symfony ^2.7.10|^3.0.3 -> satisfiable by symfony/symfony[v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9].
    - lolautruche/payline-bundle v1.1.2 requires symfony/symfony ^2.7.10|^3.0.3 -> satisfiable by symfony/symfony[v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9].
    - Conclusion: don't install symfony/symfony v3.0.3
    - Installation request for lolautruche/payline-bundle ^1.0 -> satisfiable by lolautruche/payline-bundle[v1.0.0, v1.0.1, v1.0.2, v1.1.0, v1.1.1, v1.1.2].
