### ISSUE TITLE
PHP7 type hinting

### ISSUE THREAD

**Issue by dlasserre** [lolautruche/LolautruchePaylineBundle#5]
Hi,

In WebTransaction.php file on line 464 there is a hinting type:

`
/**
     * @param string $token
     */
    public function setToken(string $token)
    {
        $this->token = $token;
    }
`

I'm not sure is very safe (compatibility)... can you fixe it for older php version (5.6) ?

PS: Are you french ? ;) how do you say "autruche" in english :p 

Thank's

**Comment by lolautruche** [comment]
Thanks for the heads up @delasserre!

> PS: Are you french ? ;) how do you say "autruche" in english :p

Yes indeed, I'm french :wink:. "autruche" means "ostrich" :smile:

**Comment by dlasserre** [comment]
Thanks for you reactivity ! ;)
