### ISSUE TITLE
Payline Error : Unauthorized

### ISSUE THREAD

**Issue by vlafranca** [lolautruche/LolautruchePaylineBundle#6]
Hi,
I am trying to set up the bundle in symfony 3 but actually I am getting an error while calling 
`$payline->initiateWebTransaction($transaction);`
Here is the payline api response : 

> object(Lolautruche\PaylineBundle\Payline\PaylineResult)[6909]
>   private 'code' => string 'XXXXX' (length=5)
>   private 'shortMessage' => string 'Unauthorized' (length=12)
>   private 'longMessage' => string 'Unauthorized' (length=12)
>   private 'resultHash' => 
>     array (size=1)
>       'result' => 
>         array (size=5)
>           'code' => string 'XXXXX' (length=5)
>           'longMessage' => string 'Unauthorized' (length=12)
>           'shortMessage' => string 'Unauthorized' (length=12)
>           'partnerCode' => null
>           'partnerCodeLabel' => null
>   private 'privateData' => 
>     array (size=0)
>       empty
>   private 'accessor' => 
>     object(Symfony\Component\PropertyAccess\PropertyAccessor)[6904]
>       private 'magicCall' => boolean false
>       private 'ignoreInvalidIndices' => boolean true
>       private 'readPropertyCache' => 
>         array (size=0)
>           empty
>       private 'writePropertyCache' => 
>         array (size=0)
>           empty

The parameters are well set, and the doWebPayment works with the payline's php samples.

Thank you in advance for your help.

**Comment by vlafranca** [comment]
Ok just found that the merchant_id and the access_key must be surrounded by double quotes ^^

**Comment by lolautruche** [comment]
Sorry for not replying :-)

Glad to see that you finally found a solution.
Thanks for using the bundle!

**Comment by smartinsalmeida** [comment]
Hi!
I get this error too !
Payline says that HOMO must be surrounded by double quotes (not in the bundle doc) and I read here that merchant_id must be too.

[2016-10-24 17:58:27] PaylineSDK.INFO: __construct {"merchant_id":"489740*******8","access_key":"X****************whF","proxy_host":null,"proxy_port":null,"proxy_login":null,"proxy_password":null,"environment":"HOMO"} []
[2016-10-24 17:58:27] PaylineSDK.INFO: doWebPaymentRequest {"order.ref":"MB#215#5#281"} []
[2016-10-24 17:58:27] PaylineSDK.ERROR: Exception occured at doWebPayment call {"code":0,"message":"Unauthorized","endpoint":"https://homologation.payline.com/V4/services/WebPaymentAPI"} []

I get this error but can't found why.

can you help me ?

PS : je suis français aussi :)

**Comment by lolautruche** [comment]
I added in the documentation that `merchant_id` and `access_key` must be surrounded by quotes.
